version: '3'

services:
  db:
    image: postgres:10
    environment:
      POSTGRES_DB: mymedia
      POSTGRES_PASSWORD: password
  app:
    build: .
    command: >
      bash -c "dockerize -wait tcp://db:5432
      && pipenv install --system --dev
      && python manage.py migrate
      && python manage.py createsuperuser_with_password --email admin@example.com --password admin
      && python manage.py collectstatic --noinput
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    working_dir: /app/mymedia
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
